config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'likes/create'
  # Defines the root path route ("/")
  # root "user#index"
  root 'user#index'

  get '/user', to: 'user#index'
  get '/user/:id', to: 'user#show'
  get '/user/:id/post', to: 'post#index', as: 'post'
  get '/user/:id/post/new', to: 'post#new'
  get '/user/:id/post/:id', to: 'post#show'
  post '/user/:id/post/create', to: 'post#create'
  get '/user/:id/post/:post_id/comments/new', to: 'comments#new'
  post '/user/:id/post/:post_id/comments/create', to: 'comments#create'
  post '/user/:id/post/:post_id/likes', to: 'post#likes', as: 'likes'
  post '/user/:id/post/:post_id/likes/create', to: 'likes#create'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    if user.admin? # additional permissions for administrators
      can :manage, :all
    else # additional permissions for users
      can :read, :all
      can :manage, Post, author_id: user.id
      can :manage, Comment, author_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :post

  # Remove redundant before_save callback
  after_save :update_comments_counter
  after_destroy :reset_comments_counter

  # Define a method to update the comments counter for a post
  def update_comments_counter
    # Use safe navigation (&.) and check for the presence of the post
    post = Post.find_by(id: post_id)
    post&.increment!(:comments_counter) if post.present?
  end

  # Define a method to reset the comments counter for a post
  def reset_comments_counter
    # Use safe navigation (&.) and check for the presence of the post
    post = Post.find_by(id: post_id)
    post&.decrement!(:comments_counter) if post.present?
  end
end

app/models/like.rb
class Like < ApplicationRecord
  # Associations
  # A like belongs to an author
  # A like belongs to a post
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :post

  after_save :update_likes_counter

  # Define a method to update the likes counter for a post

  def update_likes_counter
    Post.find_by(id: post_id).increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  # Associations
  # A post belongs to an author
  # A post has many comments
  # A post has many likes
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :comments, foreign_key: :post_id
  has_many :likes, foreign_key: :post_id

  after_save :update_posts_counter_for_user
  # before_save :update_posts_counter
  # before_save :update_user_posts_counter

  # The 3 most recent comments for a given post
  scope :recent_comments, ->(post) { post.comments.order(created_at: :desc).limit(5) }

  # Add validations
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def update_posts_counter_for_user
    author.increment!(:posts_counter) if author.present?
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  before_validation :set_default

  # :Confirmable
  # Associations
  # A user has many posts
  # A user has many comments
  # A user has many likes
  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id


  # The 3 most recent posts for a user
  scope :recent_posts, ->(user) { user.posts.order('created_at desc').limit(3) }

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def set_default
    self.posts_counter = 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:name, :bio, :email, :password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    @comment.post_id = params[:post_id]

    if @comment.save
      flash[:success] = 'Comment saved successfully'
      redirect_to '/user/:id/post/:id'
    else
      flash.now[:error] = 'Error: Comment could not be saved'
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new
    @post = Post.find(params[:post_id])
    @like.post_id = @post.id
    @like.author_id = current_user.id

    if @like.save
      redirect_back(fallback_location: root_path, notice: 'Like was successfully created.')
    else
      render :new, alert: 'Like was not created.'
    end
  end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def index
    @user = User.find(params[:id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    @post.comments_counter = 0
    @post.likes_counter = 0

    if @post.save
      flash[:success] = 'Post saved successfully'
      redirect_to post_path(@post)
    else
      flash.now[:error] = 'Error: Post could not be saved'
      render :new
    end
  end

  def likes
    @post = Post.find(params[:id])
    Like.create(author_id: current_user.id, post_id: @post.id)
    redirect_back(fallback_location: root_path)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/comments/new.html.erb
<h2>Add a Comment</h2>

<%= form_with model: @comment, url: "/user/id/post/#{params[:post_id]}/comments/create" do |form| %>
  <%= form.label :text, 'Your comment' %>
  <%= form.text_field :text %>
  <br/>
  <%= form.submit %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag 'devise', media: 'all' %>
  </head>

  <body>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/partial/_like.html.erb
<%= form_with model: model, url: url, class: 'button3', local: true do |form| %>
  <%= form.submit "Like" %>
<%end%>

app/views/partial/_user_profile.html.erb
<div class="user_container">
  <div class='user_photo'>
    <% if user.photo.present? && user.photo.match(/.(jpg|jpeg|png|gif)$/i) %>
      <%= image_tag(user.photo, alt: user.name) %>
    <% end %>
  </div>
  <div class="user_card">
    <a href="/user/<%= user.id %>" class="user_name"> <%= user.name %> </a>
    <p class="posts_counter">Number of posts: <%= user.posts_counter %></p>
  </div>
</div>

app/views/post/index.html.erb
<%= render 'partial/user_profile', user: @user %>

<div class="user_profile">
<a href="/user/<%= @user.id %>/post/new" class="button"><b>Add Post</b></a>
  <% @posts.each do |post| %>
    <div class="posts">
      <div class="user_post">
        <a href="/user/<%= post.author_id %>/post/<%= post.id %>"><b><%= post.title %></b></a>
        <p><%= post.text %></p>
        <span>Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></span>
      </div>
      <ul class="comments">
        <% Post.recent_comments(post).each do |comment|%>
          <li><b><%= comment.author.name %>:</b> <%= comment.text %></li><br/>
        <%end%>
      </ul>
      </div>
  <%end%>
  <button type="button" class="button1">Pagnation</button>
</div>

app/views/post/new.html.erb
<h2>Add a post below</h2>

<%= form_with model: @post, url: "/user/id/post/create" do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %><br/>
  <%= form.label :text %>
  <%= form.text_field :text %>
  <br/>
  <%= form.submit %>
<%end%>

app/views/post/show.html.erb
<div class="user_comment">
  <div class="post">
    <div class="post_comment">
      <h2><%= @post.title %> by <%= @post.author.name %></h2>
      <span>Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %></span>
    </div>
    <p><%= @post.text %></p>
  </div>
  <div class="btn">
    <a href="/user/<%= @post.author_id%>/post/<%= @post.id %>/comments/new" class="button">Add a comment</a>
    <%= render 'partial/like', model: @like, url: likes_path(@post, :post_id) %>
  </div>
  <ul class="comments">
    <% @post.comments.each do |comment|%>
      <li><b><%= comment.author.name %>:</b> <%= comment.text %></li><br/>
    <%end%>
  </ul>
</div>

app/views/user/index.html.erb
<h1>Welcome All Food Enthusiasts</h1>

<% @users.each do |user| %>

  <%= render 'partial/user_profile', user: user %>

<% end %>

app/views/user/show.html.erb
<%= render 'partial/user_profile', user: @user %>

<div class="user_profile">
    <div class="user_bio">
      <h3>Bio</h3>
      <p class="bio">
        <b><%= @user.bio %></b><br/><br/>
        <%= @user.name %>, a passionate food enthusiast, has embarked on a lifelong journey of exploring the world of flavors and cuisines. 
        His insatiable curiosity and love for all things culinary have led him on a delectable adventure through the vast and diverse realm of food. 
        Born and raised in a small town, <%= @user.name %>'s fascination with food began at a tender age. 
        In his family's cozy kitchen, he watched his grandmother whip up traditional recipes with love and skill. 
        Those moments sparked a culinary fire within him that would never cease to burn.
      </p>
    </div>
  <% User.recent_posts(@user).each do |post| %>
    <div class="user_post">
      <a href="/user/<%= post.author_id %>/post/<%= post.id %>"><b><%= post.title %></b></a>
      <p><%= post.text %></p>
      <span>Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></span>
    </div>
  <%end%>
    <a href="/user/<%= @user.id %>/post" class="button">See all posts</a>
</div>